name: Dart/Flutter Conventional Release
description: Automating version bump for conventional dart/flutter releases
runs:
  using: docker
  image: Dockerfile
branding:
  icon: upload-cloud
  color: blue
inputs:
  tag-prefix:
    description: "Prefix that is used for the git tag"
    default: "v"
    required: false
  use-dart:
    description: "Prefix that is used for the git tag"
    default: false
    required: false
  script-pre-run:
    description: "Path to a dart script that is executed before the version bump"
    required: false
  deploy-key:
    description: "Deploy key to use for the git push"
    required: false
